### ISSUE TITLE
Time complexity

### ISSUE THREAD

**Issue by SteveAndrewArcher** [SteveAndrewArcher/Wumpus#2]
@SC25  We failed to realize that the entails method that we got from the slides/book has time complexity 2^n. So, while I'm confident that it works the way we did it, it'll never complete because the number of models it needs to process is 2^64. Crap.

I'm going to try to replace it with the forward chaining algorithm from further on the wumpus chapter of the book. That'll mean replacing the long string knowledge base with an ArrayList of "clause" objects.

**Comment by SC25** [comment]
I realized I didn't have your contact info. Can you make it to school
today? I can be there from now until about 3pm
